### ISSUE TITLE
Feature request: Insert the template to the root node.

### ISSUE THREAD

**Issue by mzwlevi** [sawhney17/logseq-smartblocks#1]
Could you add the choice to insert template to the root node?
Such as insert timestamp, this will be useful to write journal.
Thank you!

<img width="781" alt="Screen Shot 2022-01-25 at 17 39 24" src="https://user-images.githubusercontent.com/78029539/150951765-7378f64c-4f9c-4a7f-96b1-dabb50ced210.png">

**Comment by sawhney17** [comment]
Good idea. I'll add it to the next release.

**Comment by mzwlevi** [comment]
> Good idea. I'll add it to the next release.

Thank you! The button is really nice!

**Comment by sawhney17** [comment]
@mzwlevi, added in the latest release

@itsjustmath, can you check the latest release. Is adding the sibling flag what you're looking for?

**Comment by mzwlevi** [comment]
> @mzwlevi, added in the latest release
> 
> @itsjustmath, can you check the latest release. Is adding the sibling flag what you're looking for?

Nice! I have shared this in Logseq fans group.
But there is a problem about insert time:
<img width="711" alt="Screen Shot 2022-01-26 at 11 00 57" src="https://user-images.githubusercontent.com/78029539/151097188-57d2ff2c-70e7-4d6e-a627-4b038f40bc56.png">
The `current time` do not show 0, such as the time 11:06 11:00, the insert current time was 11:6 11:0, then I need to add 0 by myself.
I have reported this issue: https://github.com/sawhney17/logseq-smartblocks/issues/2
<img width="1092" alt="Screen Shot 2022-01-26 at 11 00 41" src="https://user-images.githubusercontent.com/78029539/151097041-6da915fb-0a09-4325-9bec-0c5cc0cfc192.png">

**Comment by mzwlevi** [comment]
When using Logseq slash menu to insert current time: 
<img width="394" alt="Screen Shot 2022-01-26 at 11 20 49" src="https://user-images.githubusercontent.com/78029539/151098585-c71f4823-282c-4dd9-aba1-1fb9348cc744.png">
<img width="364" alt="Screen Shot 2022-01-26 at 11 20 56" src="https://user-images.githubusercontent.com/78029539/151098592-938fe916-206c-4adf-af5a-a6b47a755947.png">

**Comment by sawhney17** [comment]
@mzmlevi I will cut a release fixing this issue later today.

**Comment by sawhney17** [comment]
@mzwlevi it's fixed

**Comment by sawhney17** [comment]
@mzwlevi, you can also now insert inline templates using `{{renderer :smartblockInline, sampleTemplate}}`

**Comment by mzwlevi** [comment]
> @mzwlevi, you can also now insert inline templates using `{{renderer :smartblockInline, sampleTemplate}}`

👌

**Comment by itsjustmath** [comment]
> @mzwlevi, added in the latest release
> 
> @itsjustmath, can you check the latest release. Is adding the sibling flag what you're looking for?

@sawhney17 is it possible that the template replaces the button completely? As in the same block? Instead of being a sibling or child?

![CleanShot 2022-01-31 at 11 05 14@2x](https://user-images.githubusercontent.com/635044/151856470-dadf1c91-aff0-4133-a6f0-7e88c862b73b.png)

**Comment by sawhney17** [comment]
Update to the latest version, it has the option for inline smartblocks is that what you're looking for? Make sure you restart after updating.

**Comment by axelav** [comment]
I'd still love to see what @itsjustmath is looking for. When you click the button, the current block (of which the button is the content) is replaced with the template. Right now I have to click the button and then delete the original line since I don't want to button to hang around.

Does this make sense?

- "Block ABC"
- {{A Smartblock}}
- "Block ZXY"

...user clicks Smartblock...

- "Block ABC"
- "Rendered template from Smartblock, button has been replaced"
- "Block ZXY"
