### ISSUE TITLE
Inline smartblocks nested under empty bullet

### ISSUE THREAD

**Issue by mahso** [sawhney17/logseq-smartblocks#10]
When "Creating Inline Smartblock", the blocks of the given template are nested as children under an empty bullet (which is the bullet where the smartblock command was inserted). Would it be possible to not get the empty bullet and expand the template at the same level as the smartblock command is fired? Something similar to the "sibling" parameter for smartblock buttons would do the trick.

**Comment by owenjuni** [comment]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/37996646/155639706-e970b729-b3bf-4706-85e5-65d763c7ddbd.png">

**Comment by sawhney17** [comment]
Thank you :)
