### ISSUE TITLE
Random block refs invalidated after re-index

### ISSUE THREAD

**Issue by ksqsf** [sawhney17/logseq-smartblocks#11]
In the latest version (0.6.2) of logseq, after doing a full re-index, the references of random blocks created by Smart Blocks become invalid.

My use case is a simple one: it picks a random block with a certain tag. (The same as [this video](https://www.youtube.com/watch?v=pIEhIIZc2cw).)

After creating the block ref, I can jump to it via the ref, so the ID is correct. But after re-index, the ID changes. I don't know if this is a bug of Logseq, or a bug of Smart Blocks (forgetting to make the ID persist by adding it to the text file), or it is a change in logseq that Smart Blocks hasn't caught up with.

**Comment by ksqsf** [comment]
I should add that the block referenced has not been referenced before. So it's quite likely that Smart Blocks forgot to make the ID persist?

**Comment by sawhney17** [comment]
Yeah, that's likely the issue. I'll fix the issue today.

**Comment by sawhney17** [comment]
Should be fixed in the latest release
