### ISSUE TITLE
integrated setting is bugged 

### ISSUE THREAD

**Issue by lef-est** [sawhney17/logseq-smartblocks#13]
Edit: I know mod stands for command in mac and ctrl in windows. The reason I tried to change it is because when I first tried ctrl+t, it was buggy. The blinking cursor disappeared but the search panel did not come up.

![image](https://user-images.githubusercontent.com/9643637/163577183-4386e69a-e61b-4fe6-a142-8638f1b07592.png)
If I access it via Settings > Plugin Settings > logseq-smartblocks, then it is buggy: I can't really type or change anything in the text box. I tried to change it, and the result is weird: The UI shows no change at all; and in settings.json it looks like I only managed to append one or two letters to the end or a random position in the original string.

![image](https://user-images.githubusercontent.com/9643637/163577138-e3e55c12-cdf7-4488-8f4b-ab1de67f444f.png)
The setting here works. I needed to relaunch logseq but it worked in the end. The strange thing is the setting above (first screenshot) still showed "mod" for me, even though settings.json is already changed to ctrl.

**Comment by sawhney17** [comment]
Yeah it's a bug with the current version of logseq, when the next version of logseq is release this bug will be fixed.

**Comment by lef-est** [comment]
Great! I'll close this then.
