### ISSUE TITLE
Bug: When insert current time contains 0,  it will not show the 0.

### ISSUE THREAD

**Issue by mzwlevi** [sawhney17/logseq-smartblocks#2]
<img width="339" alt="Screen Shot 2022-01-25 at 18 01 55" src="https://user-images.githubusercontent.com/78029539/150955796-43ab652d-1f49-48c1-845a-8499135b50e4.png">

**Comment by sawhney17** [comment]
@mzwlevi it's fixed

**Comment by mzwlevi** [comment]
> @mzwlevi it's fixed

Happy!
