### ISSUE TITLE
Using a button with inputs creating as siblings results in data loss

### ISSUE THREAD

**Issue by hphoeksma** [sawhney17/logseq-smartblocks#22]
`{{renderer :smartblock, Add Interaction, Add Interaction, true}}` renders some inputs to record interactions. It is on top of an Interactions section on my Daily Note. When pressing the button, sometimes all next siblings will be removed resulting in data loss...

**Comment by sawhney17** [comment]
Can you replicate this in the latest version of logseq?

**Comment by hphoeksma** [comment]
https://user-images.githubusercontent.com/250683/171044384-fcf5e271-6c2e-4f98-98b4-6a6ac948f892.mov

Logseq 0.7.0

**Comment by sawhney17** [comment]
Can you check if the content remains on disk?
