### ISSUE TITLE
Some templates run but nothing is outputted

### ISSUE THREAD

**Issue by hphoeksma** [sawhney17/logseq-smartblocks#24]
This template can be selected in the insert window, shows the run has begun alert, but outputs nothing.
This used to work fine in a former release.

```md
- #SmartBlock Daily  
	- ## 🚀  MIT  
		-  
	- ## 🕧  When time  
		-  
	- ## 🤝  Interactions  
		- {{renderer(:smartblock,Add Interaction,Add Interaction,true)}}  
		-  
	- ## 📘  Notes  
		- {{renderer(:smartblock,Daily Review,Daily Review,true)}}  
		- **<%current time%>** –  
	-
```

## Errors:
<img width="729" alt="Screenshot 2022-06-08 at 10 41 50" src="https://user-images.githubusercontent.com/250683/172572896-b239ff9f-43bd-4cf8-9edd-9ef4c72d0b5a.png">

## Versions:
Logseq 0.7..2
Smartblocks 3.2.5

**Comment by BuaaLzd** [comment]
I met the same issue after updating to 0.7.2, hopefully, it could be fixed.

**Comment by sawhney17** [comment]
Try the nightly version of logseq.

**Comment by sawhney17** [comment]
There's a bug in the latest version of logseq. Try the new nighty version
