### ISSUE TITLE
反斜杆,没有出现Create templater block

### ISSUE THREAD

**Issue by uulaile** [sawhney17/logseq-smartblocks#25]
![image](https://user-images.githubusercontent.com/96331996/173177139-281e6c3f-abe8-4041-beef-de1175eab123.png)

**Comment by uulaile** [comment]
logseq 0.7.3(nightly20220610)+logseq-smartblocks3.2.5

**Comment by sawhney17** [comment]
Use create smart block button. The function has been renamed

**Comment by sawhney17** [comment]
Use Create smartblock, not create templates block. I should update the documentation.
