### ISSUE TITLE
The Cursor should autofocus in search field in smartblock insertion window

### ISSUE THREAD

**Issue by pushakargaikwad** [sawhney17/logseq-smartblocks#29]
When Triggered using the keyboard shortcut, the smartblock window pops up, with the list of available smart blocks. 

Pressing up and down arrow keys allows you to select smartblock using the keyboard.
But however, if you have to search, you must first click on the search field using the mouse. 

If the search field could auto-pull focus when it appears, the keyboard workflow will be seamless and faster.

**Comment by sawhney17** [comment]
Fixed in next version
