### ISSUE TITLE
Or/And operations in templates

### ISSUE THREAD

**Issue by bathrobe** [sawhney17/logseq-smartblocks#3]
Feature request! I imagine it's in the works but wanted to express interest.

Being able to use OR and AND in templates would be amazing.

```
- <% ifdayofweek = 1 || dayofweek = 2 || ... dayofweek = 5%>
   - Happy workweek
```

**Comment by sawhney17** [comment]
yep, that definitely sounds great. I’ll try adding it later today if I get the chance.

**Comment by sawhney17** [comment]
i've added this feature to the latest release
