### ISSUE TITLE
Call a slash command

### ISSUE THREAD

**Issue by gustavoip** [sawhney17/logseq-smartblocks#33]
I'm trying to write a template that needs, in the rendering process, to call a specific slash command. Is there a way to do that in the current version?

**Comment by sawhney17** [comment]
No. Which slash command? Is it part of another template?

**Comment by sawhney17** [comment]
Just do: 

`{{renderer :wordcount_<%randUUID%>}}`

This will create a word counter when you insert the template provided you're on the latest version of logseq.

**Comment by gustavoip** [comment]
You are fast, young man! Thanks a lot
