### ISSUE TITLE
Is there a way to let the Template overwrite the Button, instead of inserting it under the Button?

### ISSUE THREAD

**Issue by Skyryd** [sawhney17/logseq-smartblocks#37]
I build a template for my Journal with multiple Smartblock-Buttons. So I can deside, which section of the daylie journal I want to get shown....e.g. a button for "Workout", which then inserts my workout template. 

Is there any way to let the inserted template overwrite the button itself, instead of insert the template under the button?

**Comment by sawhney17** [comment]
Hmm. Maybe something like the mod+t smart block insertion window?

**Comment by Skyryd** [comment]
What do you mean with "mod+t"? 

Sorry, I'm new on GitHub:) In my case, it would be a nice feature, to get rid of the button automatically, after i clicked it. So...button clicked...template inserted...no other need for the button, cause I never want to click it again in this scenario.

**Comment by sawhney17** [comment]
Well you can click command t or control t on windows to trigger an insertion window. Or try /insert smartblock. May be better for your workflow.

**Comment by Skyryd** [comment]
Thx for your replies:) 

Maybe it's just a very niche request, but I like the idea, the button has an option to get overwritten bei clicking (inserting hier template) him.
