### ISSUE TITLE
Suppress IF statements

### ISSUE THREAD

**Issue by BrianBarry** [sawhney17/logseq-smartblocks#4]
When an IF statement is executed, the IF statement itself should be suppressed. 

So: TODO IF xxx Do something
should render as

TODO Do something

**Comment by sawhney17** [comment]
This should already be the behavior, is this not working for you? Could you send a screenshot of the template?
<img width="644" alt="Screen Shot 2022-01-26 at 4 39 58 PM" src="https://user-images.githubusercontent.com/80150109/151164534-8f84fe85-379d-4fdd-a1e5-83ea5c7d9979.png">

**Comment by BrianBarry** [comment]
You are correct. I obviously was doing something wrong. 

Brian
