### ISSUE TITLE
Random Function Smartblock Button Returning Undefined

### ISSUE THREAD

**Issue by Gorpokki** [sawhney17/logseq-smartblocks#41]
Using Logseq v0.8.7 and logseq-smartblocks v3.5.0.

Given the following definition: 
![image](https://user-images.githubusercontent.com/113131459/190545621-b463be3f-ee62-487e-8326-9833faf42547.png)

The button now returns this instead of a random block:
![image](https://user-images.githubusercontent.com/113131459/190546135-f166c440-942a-42d6-9dc6-29df3f8b19df.png)

**Comment by sawhney17** [comment]
Are you by chance in a journal page. Does clicking the title to open the page in fulls green work?

**Comment by Gorpokki** [comment]
> Are you by chance in a journal page. Does clicking the title to open the page in fulls green work?
> […](#)
> On 16 Sep 2022 at 6:50 AM +0400, Gorpokki ***@***.***>, wrote: Given the following definition: The button now returns this instead of a random block: — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Yes, using the button on a journal page. Opening the full page and trying to use the button uses the same result.

Additionally, trying to call the smartblock from a slash command also returns an `undefined`

**Comment by sawhney17** [comment]
Can you replicate this on another page. Like a plain page called "Smartblcoks"

**Comment by Gorpokki** [comment]
> Can you replicate this on another page. Like a plain page called "Smartblcoks"
> […](#)
> On 16 Sep 2022 at 4:41 PM +0400, Gorpokki ***@***.***>, wrote: > Are you by chance in a journal page. Does clicking the title to open the page in fulls green work? > … > On 16 Sep 2022 at 6:50 AM +0400, Gorpokki @.>, wrote: Given the following definition: The button now returns this instead of a random block: — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Yes, using the button on a journal page. Opening the full page and trying to use the button uses the same result. Additionally, trying to call the smartblock from a slash command also returns an undefined — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Same result, `((undefined))`

**Comment by wirtzdan** [comment]
Same for me! Also using it on the journal page.

**Comment by sawhney17** [comment]
Found the issue. Will push a release within the hour.

**Comment by sawhney17** [comment]
Try the latest update .
