### ISSUE TITLE
DATEBASIS and User Input

### ISSUE THREAD

**Issue by BrianBarry** [sawhney17/logseq-smartblocks#5]
You are doing an amazing job porting SMARTBLOCKS from Roam to Logseq. I've attached a copy of a SmartBlock that works in Roam that has features you may want to consider. Used together they permit creation of a "recurring project" Smartblock -- capable of not just adding, but also scheduling dozens of actions in seconds. They can be used for a wide variety of things, e.g., releasing an update, onboarding a new hire, initiating a contract, closing sequence for a home buyer, publishing a newsletter and many other things. Variables, DATEBASIS, and date arithmetic relative to a DATE set by a variable and changed as necessary by DATEBASIS. 

-  #42SmartBlock Trip Test #sample_recurring_project
    - <%SET: Destination, <%INPUT: What is your destination?%>%> <%NOBLOCKOUTPUT%>
    - <%SET: projectStart, <%INPUT: On what date does the travel start?%>%>
    - <%NOBLOCKOUTPUT%>
    - **Metadata**
        - **Status**: Active
        - **Review Periodicity**
        - **Goals**
        - **Reference Notes**
    - **Tasks**
        - {{[[TODO]]}} Add the project:<%CURRENTPAGENAME%> to the List  of Projects #next
        - {{[[TODO]]}} Assign a review periodicity to the project:<%CURRENTPAGENAME%> and update Recurring Actions SmartBlock #next
        - {{[[TODO]]}} Create a WorkBench Inbox action for the project:<%CURRENTPAGENAME%>: #next
        - {{[[TODO]]}} Add<%CURRENTPAGENAME%> to the Keyboard  Maestro WorkBench conflict pallet #next
        - {{[[TODO]]}} Plan<%CURRENTPAGENAME%>#next
        -  <%DATEBASIS: <%GET: projectStart%>%>
        - {{[[TODO]]}} <%DATE:**15 days ago**%> Make Plane reservations for <%GET: Destination%> #scheduled
        - {{[[TODO]]}} <%DATE:**12 days ago**%> Make hotel and car reservations for <%GET: Destination%> #scheduled
        - {{[[TODO]]}} <%DATE:**2 days ago**%> Board the dog #scheduled
        - {{[[TODO]]}} <%DATE:**TODAY**%> Start Trip to <%GET: Destination%> #scheduled
        - {{[[TODO]]}} <%DATE:**2 days from now**%> Give presentation to the Board #scheduled
    - **Close-out**
        - {{[[TODO]]}} Archive<%CURRENTPAGENAME%>. #project-closeout
        - {{[[TODO]]}} Remove<%CURRENTPAGENAME%> from the Recurring Actions SmartBlock section for project reviews. #project-closeout
        - {{[[TODO]]}} Remove<%CURRENTPAGENAME%> from the Keyboard Maestro WorkBench conflict pallet. #project-closeout.
        - {{[[TODO]]}} When complete, consider<%CURRENTPAGENAME%> for possible reuse. #project-closeout

**Comment by sawhney17** [comment]
Could you elaborate a bit more on databasis? I'm currently working on the currentpagename block. Already have a working build, just a bit buggy.

**Comment by BrianBarry** [comment]
DATEBASIS used in a SmartBlock does one of two things:

- Calculates IF statements based on the date of the current DNP, or
- Calculates IF statements based on setting it to a variable intialized by the user.

In the first case DATEBASIS allows you to see what will be due on a future DNP. Neither Logseq nor Obsidian have this capability now. 

In the second case it works in combination with a couple of other features:
- The ability to assign an arbitrary (user supplied) date to a variable.
- The ability to change DATEBASIS to the value of a variable during the execution of a SmartBlock
- The ability to calculate dates relative to a date assigned by DATEBASIS

This capability allows a user to create Smartblocks that make use of one or several key event dates. For example, assume that you are tasked with publishing a quarterly newsletter. There are a set of standard tasks associated with this process, that must be performed on dates relative to (before, on, or after) different key events. The key events might be: Complete Initial Layout, Send Newsletter to Printer, Mail Newsletter.  

As the SmartBlock executes, DATEBASIS would be reassigned, permitting tasks to be scheduled — offset againste each key event date in sequence. 

The value of this system increases as the project’s complexity increases. For example, consider a teacher responsible for the annual school play. There might be a half-dozen key events and a couple of hundred tasks that need to be scheduled. 

I hope that this clarifies the request. Please don’t hestitate to ask for more information. You ability to port SmartBlocks is truly amazing. 

Brian

**Comment by BrianBarry** [comment]
More info re DATEBASIS. 

Using the example below that is a “standard business trip” that employs two different key event dates. The arrows:

Red: Name of trip and set the two key event dates to the variables: projectStart and projectEnd

Orange: Add standard project initialization tasks — they are always done when a new project is first created.

Green: Use DATEBASIS to perform date calculations relative to the start of the trip. 

Blue: Change DATEBASIS to perform date calculations relative to the return date. 

Brown: Standard close-out tasks. 

This SmartBlock can be used as the basis for any travel. The example is obviously not complete — just enough to show how it might work in a real setting. The value for this kind of “recurring project” is that tasks are not just initialized, they are also scheduled. There might be dozens of them scheduled in this manner. Depending upon a person’s job, there might be a few dozen of these recurring projects. 

The value of this approach increases as the recurring project’s complexity increases. 

Brian

**Comment by BrianBarry** [comment]
Still more info on DATEBASIS.

Using a template  to create the DNP structure, this appears:



The arrow points to a button that executes a SmartBlock. The following screenshot shows the first few IF statements associated with this SmartBlock. There are actually many more, reflecting what I believe is the importance of the recurring action concept to productivity. 

The arrow points to the use of DATEBASIS when set to the value of the DNP on which this Smartblock is executed. This allows you to see what will be due tomorrow or next Thursday — you just need to initialize the structure for a future DNP and then press the Recurring button. From a planning standpoint it is very valuable. 

Brian

**Comment by sawhney17** [comment]
i've added support for <%currentpage%> to insert the current page. I'm still working on your other suggestions.

**Comment by sawhney17** [comment]
At the moment now, everything should work execpt for the destination and project start input blocks.

**Comment by BrianBarry** [comment]
Amazing!

**Comment by sawhney17** [comment]
Latest release should have support for inputs!
