### ISSUE TITLE
Date  should honour Logseq   date format settings 

### ISSUE THREAD

**Issue by danieltomasz** [sawhney17/logseq-smartblocks#7]
Again, many thanks for making/porting this plugin!

My request: date format should depend from Logseq EDN settings
currently, when I use the template `<%Today%>` I am getting  `[[Jan 26th, 2022]]`, but I am expecting  `[[2022-01-26]]`

In my `config.edn` I have
```
 :date-formatter "yyyy-MM-dd"
```
I would propose for the plugin to inherit those settings for date format

**Comment by sawhney17** [comment]
It  should ideally already be doing that. it doesn’t use the config.edn value but rather the value that you deifned in the in built settings. Date formatter is not the official or recommended approach to setting the date format. Could you try setting this in config.edn `:journal/page-title-format "MMM do, yyyy”`or perhaps setting the date format from settings? It creates a slightly different config.edn entry and that’s what’s taken as input

**Comment by sawhney17** [comment]
That seems like a bug then. I'll be investigating it

**Comment by sawhney17** [comment]
Found the cause. Looks like the date format is getting stuck in cache. It's an issue when changing the date format after the plugin has already been installed. Try reinstalling the plugin.

**Comment by danieltomasz** [comment]
Yes, reinstalling the plugin solved it! Thanks!
But I didnt change the format after I installed the plugin. I will mark it as solved anyway.

**Comment by danieltomasz** [comment]
today `{{renderer :smartblock, today-date,Today, true}}` it was  back displaying [[Jan 30th, 2022]] format, after reinstall it come back to [[2022-01-30]]

**Comment by sawhney17** [comment]
I believe this new release should solve it for good. Looks like the date format was not staying in sync with Logseq's and only refreshed once the whole plugin was refreshed.
