### ISSUE TITLE
Feedback: Hey really nice work with the plugin. Is there a way to contact you?

### ISSUE THREAD

**Issue by bonniesimon** [sawhney17/logseq-smartblocks#9]
Hey Sawhney,
I would love to learn how to create plugins for logseq. I want to contribute to logseq and logseq plugins but I have no idea on how to do it. Could you give me a way to contact you so that I can learn how to contribute to logseq from you. Like I don't know how to set up a logseq plugin project.

Also you said ping me on twitter, but your DMs are turned off. So I can't seem to contact you that way. 

Thank you.

**Comment by sawhney17** [comment]
You should be able to contact me now on twitter. I'm also on the logseq discord as Sawhney so you can contact me there as well if it's better.
